# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0002_auto_20160129_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Medico', 'verbose_name_plural': 'Medico'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
