# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_paciente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('eslogan', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.ImageField(upload_to='home')),
            ],
        ),
    ]
