# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0005_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
